# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }
plugins:
  - rubocop-rspec
  - rubocop-rails

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Width: 2

RSpec/AlignLeftLetBrace:
  Enabled: true
